### ISSUE TITLE
OS_OPEN_URL

### ISSUE THREAD

**Issue by DigitalStealth** [platformio/platformio-home#1126]
TypeError: Cannot read property 'startsWith' of null
    at http://127.0.0.1:8010/main.41f8f139cb24471f6801.min.js:1:21188
    at Generator.next (<anonymous>)
    at h (http://127.0.0.1:8010/vendor.2ac160d787125691b6aa.min.js:27:14163)
    at J (http://127.0.0.1:8010/vendor.2ac160d787125691b6aa.min.js:27:13951)
    at http://127.0.0.1:8010/vendor.2ac160d787125691b6aa.min.js:27:10567
    at v (http://127.0.0.1:8010/vendor.2ac160d787125691b6aa.min.js:27:7034)
    at H.(anonymous function) (http://127.0.0.1:8010/vendor.2ac160d787125691b6aa.min.js:27:10547)
    at http://127.0.0.1:8010/vendor.2ac160d787125691b6aa.min.js:27:13755
    at m (http://127.0.0.1:8010/vendor.2ac160d787125691b6aa.min.js:27:14697)
    at h (http://127.0.0.1:8010/vendor.2ac160d787125691b6aa.min.js:27:14223)

**Comment by valeros** [comment]
Hi @DigitalStealth ! Please run `pio update` in the IDE terminal and try again. If the error persists, please reopen the issue.
