### ISSUE TITLE
Could not initialize project

### ISSUE THREAD

**Issue by mlongo95** [platformio/platformio-home#1685]
Just tried to do a brand new install of PlatformIO on my new desktop and for some reason I'm getting this weird error while trying to create a new project.

```Server` error: {"type":"FileNotFoundError","args":[2,"The system cannot find the file specified"],"message":"[WinError 2] The system cannot find the file specified: 'C:\\\\Users\\\\Marco\\\\Documents\\\\PlatformIO\\\\Projects\\\\espserial'"}```

Any ideas what it could be?

**Comment by mlongo95** [comment]
This is what I get when I try to manually initialize a new project via the CLI using ```pio project init```
```PS C:\Users\Marco\Documents\PlatformIO\Projects> pio project init

The current working directory C:\Users\Marco\Documents\PlatformIO\Projects will be used for the project.

The next files/directories have been created in C:\Users\Marco\Documents\PlatformIO\Projects
include - Put project header files here
lib - Put here project specific (private) libraries
src - Put project source files here
platformio.ini - Project Configuration File
Error: Traceback (most recent call last):
  File "c:\users\marco\.platformio\penv\lib\site-packages\platformio\__main__.py", line 109, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "c:\users\marco\.platformio\penv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\marco\.platformio\penv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\marco\.platformio\penv\lib\site-packages\platformio\commands\__init__.py", line 44, in invoke
    return super(PlatformioCLI, self).invoke(ctx)
  File "c:\users\marco\.platformio\penv\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\marco\.platformio\penv\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\marco\.platformio\penv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\marco\.platformio\penv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\marco\.platformio\penv\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\marco\.platformio\penv\lib\site-packages\platformio\commands\project.py", line 175, in project_init
    init_base_project(project_dir)
  File "c:\users\marco\.platformio\penv\lib\site-packages\platformio\commands\project.py", line 223, in init_base_project
    config.save()
  File "c:\users\marco\.platformio\penv\lib\site-packages\platformio\project\config.py", line 468, in save
    with open(path or self.path, "w+") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Marco\\Documents\\PlatformIO\\Projects\\platformio.ini'

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================```
