### ISSUE TITLE
Internal Store Exception

### ISSUE THREAD

**Issue by cevierix** [platformio/platformio-home#266]
TypeError: Object.fromEntries is not a function
    at mapPropsToFields (http://127.0.0.1:8010/main.4e06ddad8e04e9c193bb.min.js:1:371121)
    at t.getInitialState (http://127.0.0.1:8010/vendor.c6dbe299f6639d42128d.min.js:49:65873)
    at new t (http://127.0.0.1:8010/vendor.c6dbe299f6639d42128d.min.js:19:338369)
    at xi (http://127.0.0.1:8010/vendor.c6dbe299f6639d42128d.min.js:57:51168)
    at $a (http://127.0.0.1:8010/vendor.c6dbe299f6639d42128d.min.js:57:67956)
    at xc (http://127.0.0.1:8010/vendor.c6dbe299f6639d42128d.min.js:57:105945)
    at Pl (http://127.0.0.1:8010/vendor.c6dbe299f6639d42128d.min.js:57:90235)
    at El (http://127.0.0.1:8010/vendor.c6dbe299f6639d42128d.min.js:57:90160)
    at Ml (http://127.0.0.1:8010/vendor.c6dbe299f6639d42128d.min.js:57:87500)
    at http://127.0.0.1:8010/vendor.c6dbe299f6639d42128d.min.js:57:45830

**Comment by cevierix** [comment]
Sorry, seems to be duplicate to #181
