### ISSUE TITLE
Fresh install: Cannot install libraries

### ISSUE THREAD

**Issue by jangofett4** [platformio/platformio-home#298]
## Host machine
 - Windows 10 1903 (build 18362.535)  
 - Python 3.7.1
 - pip 19.3.1

## How to reproduce
1. Install PlatformIO VSCode extension
2. Create a new project (Arduino UNO)
3. Install a library (say, DHT library by adafruit)
4. Does not work: ![crash](https://user-images.githubusercontent.com/19552452/72259205-ed852200-3620-11ea-9b8a-7ca35ce236aa.png)    
Full formatted output:
```
PIO Core Call Error: "Library Storage: C:\Users\Yahya Gedik\.platformio\lib
LibraryManager: Installing id=19 @ ^1.3.8


Error: Traceback (most recent call last):
 File "c:\users\yahya gedik\.platformio\penv\lib\site-packages\platformio\__main__.py", line 102, in main
 cli() # pylint: disable=no-value-for-parameter
 File "c:\users\yahya gedik\.platformio\penv\lib\site-packages\click\core.py", line 764, in __call__
 return self.main(*args, **kwargs)
 File "c:\users\yahya gedik\.platformio\penv\lib\site-packages\click\core.py", line 717, in main
 rv = self.invoke(ctx)
 File "c:\users\yahya gedik\.platformio\penv\lib\site-packages\platformio\commands\__init__.py", line 44, in invoke
 return super(PlatformioCLI, self).invoke(ctx)
 File "c:\users\yahya gedik\.platformio\penv\lib\site-packages\click\core.py", line 1137, in invoke
 return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "c:\users\yahya gedik\.platformio\penv\lib\site-packages\click\core.py", line 1137, in invoke
 return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "c:\users\yahya gedik\.platformio\penv\lib\site-packages\click\core.py", line 956, in invoke
 return ctx.invoke(self.callback, **ctx.params)
 File "c:\users\yahya gedik\.platformio\penv\lib\site-packages\click\core.py", line 555, in invoke
 return callback(*args, **kwargs)
 File "c:\users\yahya gedik\.platformio\penv\lib\site-packages\click\decorators.py", line 17, in new_func
 return f(get_current_context(), *args, **kwargs)
 File "c:\users\yahya gedik\.platformio\penv\lib\site-packages\platformio\commands\lib.py", line 151, in lib_install
 library, silent=silent, interactive=interactive, force=force
 File "c:\users\yahya gedik\.platformio\penv\lib\site-packages\platformio\managers\lib.py", line 301, in install
 force=force,
 File "c:\users\yahya gedik\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 698, in install
 pkg_dir = self._install_from_piorepo(name, requirements)
 File "c:\users\yahya gedik\.platformio\penv\lib\site-packages\platformio\managers\lib.py", line 151, in _install_from_piorepo
 requirements,
 File "c:\users\yahya gedik\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 480, in _install_from_url
 self.unpack(dlpath, tmp_dir)
 File "c:\users\yahya gedik\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 218, in unpack
 with FileUnpacker(source_path) as fu:
 File "c:\users\yahya gedik\.platformio\penv\lib\site-packages\platformio\unpacker.py", line 129, in __enter__
 self._unpacker = TARArchive(self.archpath)
 File "c:\users\yahya gedik\.platformio\penv\lib\site-packages\platformio\unpacker.py", line 51, in __init__
 super(TARArchive, self).__init__(tarfile_open(archpath))
 File "C:\Users\Yahya Gedik\AppData\Local\Programs\Python\Python37\lib\tarfile.py", line 1578, in open
 raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
 `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
 https://docs.platformio.org/page/faq.html

* Report this problem to the developers
 https://github.com/platformio/platformio-core/issues

============================================================"
```
Output had all kinds of wrong formatting (like \r\n's or \\ appearing), so I re-formatted it by hand.

**Comment by jangofett4** [comment]
I saw the last two-three lines now, It can't unpack the downloaded library? I'm a little bit foreign to python so this is an assumption.
