### ISSUE TITLE
Platform IO and Project Errors

### ISSUE THREAD

**Issue by altimmons** [platformio/platformio-home#3029]
Server error: {"type":"AssertionError","args":[],"message":""}

Could not load recent projects
Server error: {"type":"AssertionError","args":[],"message":""}

Im sorry I cannot provide more, Its always something. Ive reinstalled several times.

Right at this moment, this error pops up.  It said report so I am reporting.

Currently I am trying to build the Marlin Firmware for 3d Printers in VS Code, Platform IO.

Often times I cant get "home" to open, it says things like unable to start server, or server already started.

I have tried uninstalling and reinstalling.

How can I get an *entirely* clean slate, because uninstalling via VS Code, must be leaving some screwed up config in place.

I think I have also gone after the program files/data it installs as well in the past.

**Comment by altimmons** [comment]
I copied a traceback.  I did clean it up to read a lot better, from a blob of text, adding new lines, code markers, and bold.  Those are mine so if theyre weird ignore them.

## PIO Core Call Error: "Error: Traceback (most recent call last):

File "C:\\Users\\andyt\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py", line 109, in **main** cli() # pylint: 
   `disable=no-value-for-parameter``

File "C:\\Users\\andyt\\.platformio\\penv\\lib\\site-packages\\click\\core.py", line 829, in **__call__**
   `return self.main(*args, **kwargs)`

File "C:\\Users\\andyt\\.platformio\\penv\\lib\\site-packages\\click\\core.py", line 782, in **main**
   `rv = self.invoke(ctx)`

File "C:\\Users\\andyt\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py", line 44, in **invoke**
   `return super(PlatformioCLI, self).invoke(ctx)`

File "C:\\Users\\andyt\\.platformio\\penv\\lib\\site-packages\\click\\core.py", line 1259, in **invoke**
   `return _process_result(sub_ctx.command.invoke(sub_ctx))`

File "C:\\Users\\andyt\\.platformio\\penv\\lib\\site-packages\\click\\core.py", line 1066, in **invoke**
   `return ctx.invoke(self.callback, **ctx.params)`

File "C:\\Users\\andyt\\.platformio\\penv\\lib\\site-packages\\click\\core.py", line 610, in **invoke**
   `return callback(*args, **kwargs)`

File "C:\\Users\\andyt\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\boards.py", line 31, in **cli**
   `return _print_boards_json(query, installed)`

File "C:\\Users\\andyt\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\boards.py", line 80, in **_print_boards_json**
for board in **_get_boards(installed**):

File "C:\\Users\\andyt\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\boards.py", line 75, in **_get_boards**
   `return pm.get_installed_boards() if installed else pm.get_all_boards()`

File "C:\\Users\\andyt\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\manager\\platform.py", line 147, in **get_all_boards**
   `boards = self.get_installed_boards()`

File "C:\\Users\\andyt\\.platformio\\penv\\lib\\site-packages\\platformio\\util.py", line 51, in **wrapper**
   `self.cache[key] = (time.time(), func(*args, **kwargs))`

File "C:\\Users\\andyt\\.platformio\\penv\\lib\\site-packages\\platformio\\package\\manager\\platform.py", line 135, in **get_installed_boards** for config in **p.get_boards().values():**

File "C:\\Users\\andyt\\.platformio\\platforms\\atmelsam\\platform.py", line 109, in **get_boards**
   `result[key] = self._add_default_debug_tools(result[key])`

File "C:\\Users\\andyt\\.platformio\\platforms\\atmelsam\\platform.py", line 152, in **_add_default_debug_tools**
   `assert openocd_chipname`
AssertionError

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
`pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
https://docs.platformio.org/page/faq.html

* Report this problem to the developers
https://github.com/platformio/platformio-core/issues

============================================================"
