### ISSUE TITLE
Libraries: Could not install library

### ISSUE THREAD

**Issue by Mayukijin** [platformio/platformio-home#439]
Suddenly, it happened... I don't understand.  Before it was working perfectly... I just uninstalled and installed again 

PIO Core Call Error: "Library Storage: C:\\Users\\PC048\\.platformio\\lib\r\nLibraryManager: Installing id=942 @ ^2.27.6\r\n\n\nError: Traceback (most recent call last):\r\n  File \"C:\\Users\\PC048\\.platformio\\python37\\lib\\shutil.py\", line 566, in move\r\n    os.rename(src, real_dst)\r\nPermissionError: [WinError 5] Acesso negado: 'C:\\\\Users\\\\PC048\\\\.platformio\\\\lib\\\\U8g2_ID942' -> 'C:\\\\Users\\\\PC048\\\\.platformio\\\\lib\\\\U8g2_ID942@0.0.0'\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\PC048\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 102, in main\r\n    cli()  # pylint: disable=no-value-for-parameter\r\n  File \"C:\\Users\\PC048\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 764, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"C:\\Users\\PC048\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 717, in main\r\n    rv = self.invoke(ctx)\r\n  File \"C:\\Users\\PC048\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 44, in invoke\r\n    return super(PlatformioCLI, self).invoke(ctx)\r\n  File \"C:\\Users\\PC048\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1137, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"C:\\Users\\PC048\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1137, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"C:\\Users\\PC048\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 956, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"C:\\Users\\PC048\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 555, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"C:\\Users\\PC048\\.platformio\\penv\\lib\\site-packages\\click\\decorators.py\", line 17, in new_func\r\n    return f(get_current_context(), *args, **kwargs)\r\n  File \"C:\\Users\\PC048\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\lib.py\", line 151, in lib_install\r\n    library, silent=silent, interactive=interactive, force=force\r\n  File \"C:\\Users\\PC048\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\lib.py\", line 278, in install\r\n    force=force,\r\n  File \"C:\\Users\\PC048\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 700, in install\r\n    pkg_dir = self._install_from_piorepo(name, requirements)\r\n  File \"C:\\Users\\PC048\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\lib.py\", line 128, in _install_from_piorepo\r\n    requirements,\r\n  File \"C:\\Users\\PC048\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 499, in _install_from_url\r\n    return self._install_from_tmp_dir(_tmp_dir, requirements)\r\n  File \"C:\\Users\\PC048\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 569, in _install_from_tmp_dir\r\n    shutil.move(pkg_dir, join(self.package_dir, target_dirname))\r\n  File \"C:\\Users\\PC048\\.platformio\\python37\\lib\\shutil.py\", line 578, in move\r\n    rmtree(src)\r\n  File \"C:\\Users\\PC048\\.platformio\\python37\\lib\\shutil.py\", line 516, in rmtree\r\n    return _rmtree_unsafe(path, onerror)\r\n  File \"C:\\Users\\PC048\\.platformio\\python37\\lib\\shutil.py\", line 395, in _rmtree_unsafe\r\n    _rmtree_unsafe(fullname, onerror)\r\n  File \"C:\\Users\\PC048\\.platformio\\python37\\lib\\shutil.py\", line 400, in _rmtree_unsafe\r\n    onerror(os.unlink, fullname, sys.exc_info())\r\n  File \"C:\\Users\\PC048\\.platformio\\python37\\lib\\shutil.py\", line 398, in _rmtree_unsafe\r\n    os.unlink(fullname)\r\nPermissionError: [WinError 32] O arquivo já está sendo usado por outro processo: 'C:\\\\Users\\\\PC048\\\\.platformio\\\\lib\\\\U8g2_ID942\\\\src\\\\U8x8lib.h'\r\n\r\n============================================================\r\n\r\nAn unexpected error occurred. Further steps:\r\n\r\n* Verify that you have the latest version of PlatformIO using\r\n  `pip install -U platformio` command\r\n\r\n* Try to find answer in FAQ Troubleshooting section\r\n  https://docs.platformio.org/page/faq.html\r\n\r\n* Report this problem to the developers\r\n  https://github.com/platformio/platformio-core/issues\r\n\r\n============================================================"

**Comment by Mayukijin** [comment]
> Suddenly, it happened... I don't understand. Before it was working perfectly... I just uninstalled and installed again
> 
> PIO Core Call Error: "Library Storage: C:\Users\PC048\.platformio\lib\r\nLibraryManager: Installing id=942 @ ^2.27.6\r\n\n\nError: Traceback (most recent call last):\r\n File "C:\Users\PC048\.platformio\python37\lib\shutil.py", line 566, in move\r\n os.rename(src, real_dst)\r\nPermissionError: [WinError 5] Acesso negado: 'C:\\Users\\PC048\\.platformio\\lib\\U8g2_ID942' -> 'C:\\Users\\PC048\\.platformio\\lib\\U8g2_ID942@0.0.0'\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n File "C:\Users\PC048\.platformio\penv\lib\site-packages\platformio\**main**.py", line 102, in main\r\n cli() # pylint: disable=no-value-for-parameter\r\n File "C:\Users\PC048\.platformio\penv\lib\site-packages\click\core.py", line 764, in **call**\r\n return self.main(*args, **kwargs)\r\n File "C:\Users\PC048\.platformio\penv\lib\site-packages\click\core.py", line 717, in main\r\n rv = self.invoke(ctx)\r\n File "C:\Users\PC048\.platformio\penv\lib\site-packages\platformio\commands\**init**.py", line 44, in invoke\r\n return super(PlatformioCLI, self).invoke(ctx)\r\n File "C:\Users\PC048\.platformio\penv\lib\site-packages\click\core.py", line 1137, in invoke\r\n return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n File "C:\Users\PC048\.platformio\penv\lib\site-packages\click\core.py", line 1137, in invoke\r\n return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n File "C:\Users\PC048\.platformio\penv\lib\site-packages\click\core.py", line 956, in invoke\r\n return ctx.invoke(self.callback, **ctx.params)\r\n File "C:\Users\PC048\.platformio\penv\lib\site-packages\click\core.py", line 555, in invoke\r\n return callback(*args, **kwargs)\r\n File "C:\Users\PC048\.platformio\penv\lib\site-packages\click\decorators.py", line 17, in new_func\r\n return f(get_current_context(), _args, __kwargs)\r\n File "C:\Users\PC048\.platformio\penv\lib\site-packages\platformio\commands\lib.py", line 151, in lib_install\r\n library, silent=silent, interactive=interactive, force=force\r\n File "C:\Users\PC048\.platformio\penv\lib\site-packages\platformio\managers\lib.py", line 278, in install\r\n force=force,\r\n File "C:\Users\PC048\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 700, in install\r\n pkg_dir = self._install_from_piorepo(name, requirements)\r\n File "C:\Users\PC048\.platformio\penv\lib\site-packages\platformio\managers\lib.py", line 128, in _install_from_piorepo\r\n requirements,\r\n File "C:\Users\PC048\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 499, in _install_from_url\r\n return self._install_from_tmp_dir(_tmp_dir, requirements)\r\n File "C:\Users\PC048\.platformio\penv\lib\site-packages\platformio\managers\package.py", line 569, in _install_from_tmp_dir\r\n shutil.move(pkg_dir, join(self.package_dir, target_dirname))\r\n File "C:\Users\PC048\.platformio\python37\lib\shutil.py", line 578, in move\r\n rmtree(src)\r\n File "C:\Users\PC048\.platformio\python37\lib\shutil.py", line 516, in rmtree\r\n return _rmtree_unsafe(path, onerror)\r\n File "C:\Users\PC048\.platformio\python37\lib\shutil.py", line 395, in _rmtree_unsafe\r\n _rmtree_unsafe(fullname, onerror)\r\n File "C:\Users\PC048\.platformio\python37\lib\shutil.py", line 400, in _rmtree_unsafe\r\n onerror(os.unlink, fullname, sys.exc_info())\r\n File "C:\Users\PC048\.platformio\python37\lib\shutil.py", line 398, in _rmtree_unsafe\r\n os.unlink(fullname)\r\nPermissionError: [WinError 32] O arquivo já está sendo usado por outro processo: 'C:\\Users\\PC048\\.platformio\\lib\\U8g2_ID942\\src\\U8x8lib.h'\r\n\r\n============================================================\r\n\r\nAn unexpected error occurred. Further steps:\r\n\r\n_ Verify that you have the latest version of PlatformIO using\r\n `pip install -U platformio` command\r\n\r\n_ Try to find answer in FAQ Troubleshooting section\r\n [https://docs.platformio.org/page/faq.html\r\n\r\n](https://docs.platformio.org/page/faq.html%5Cr%5Cn%5Cr%5Cn)_ Report this problem to the developers\r\n [https://github.com/platformio/platformio-core/issues\r\n\r\n============================================================](https://github.com/platformio/platformio-core/issues%5Cr%5Cn%5Cr%5Cn============================================================)"
