### ISSUE TITLE
Cannot install dependencies with npm

### ISSUE THREAD

**Issue by Th2mas** [platformio/platformio-home#4624]
System info:

- OS: Windows 10 (64 Bit)
- Processor: AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx 2.30 GHz, x64-based processor
- RAM: 8.00 GB (5.94 GB usable)
- NPM version: 8.7.0
- Node version: v16.14.0

Description:

When trying to install the dependencies on the develop branch via `npm i`, I get the following error

![grafik](https://user-images.githubusercontent.com/18039357/180139896-97bcf890-2711-4467-aae5-0a8792879d37.png)

The log file:
```
0 verbose cli C:\Program Files\nodejs\node.exe C:\Users\tkhle\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@8.7.0
2 info using node@v16.14.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 6ms
5 timing config:load:file:C:\Users\tkhle\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 6ms
6 timing config:load:builtin Completed in 7ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:C:\Users\tkhle\Desktop\OpenSource\platformio-home\.npmrc Completed in 1ms
10 timing config:load:project Completed in 6ms
11 timing config:load:file:C:\Users\tkhle\.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\tkhle\AppData\Roaming\npm\etc\npmrc Completed in 3ms
14 timing config:load:global Completed in 3ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 3ms
17 timing config:load:setEnvs Completed in 4ms
18 timing config:load Completed in 37ms
19 timing npm:load:configload Completed in 39ms
20 timing npm:load:mkdirpcache Completed in 4ms
21 timing npm:load:mkdirplogs Completed in 3ms
22 verbose title npm i
23 verbose argv "i"
24 timing npm:load:setTitle Completed in 2ms
25 timing config:load:flatten Completed in 12ms
26 timing npm:load:display Completed in 16ms
27 verbose logfile logs-max:10 dir:C:\Users\tkhle\AppData\Local\npm-cache\_logs
28 verbose logfile C:\Users\tkhle\AppData\Local\npm-cache\_logs\2022-07-21T05_43_18_225Z-debug-0.log
29 timing npm:load:logFile Completed in 16ms
30 timing npm:load:timers Completed in 1ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 84ms
33 timing arborist:ctor Completed in 2ms
34 silly logfile start cleaning logs, removing 1 files
35 silly logfile done cleaning log files
36 timing idealTree Completed in 18ms
37 timing command:i Completed in 75ms
38 verbose stack TypeError: workspaces config expects an Array
38 verbose stack     at getError (C:\Users\tkhle\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\map-workspaces\lib\index.js:66:24)
38 verbose stack     at getPatterns (C:\Users\tkhle\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\map-workspaces\lib\index.js:36:11)
38 verbose stack     at mapWorkspaces (C:\Users\tkhle\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\map-workspaces\lib\index.js:82:20)
38 verbose stack     at Arborist.[loadWorkspaces] (C:\Users\tkhle\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\load-workspaces.js:22:30)
38 verbose stack     at C:\Users\tkhle\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:320:42
38 verbose stack     at async Arborist.buildIdealTree (C:\Users\tkhle\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:213:7)
38 verbose stack     at async Promise.all (index 1)
38 verbose stack     at async Arborist.reify (C:\Users\tkhle\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:153:5)
38 verbose stack     at async Install.exec (C:\Users\tkhle\AppData\Roaming\npm\node_modules\npm\lib\commands\install.js:150:5)
38 verbose stack     at async module.exports (C:\Users\tkhle\AppData\Roaming\npm\node_modules\npm\lib\cli.js:78:5)
39 verbose cwd C:\Users\tkhle\Desktop\OpenSource\platformio-home
40 verbose Windows_NT 10.0.19044
41 verbose node v16.14.0
42 verbose npm  v8.7.0
43 error code EWORKSPACESCONFIG
44 error workspaces config expects an Array
45 verbose exit 1
46 timing npm Completed in 544ms
47 verbose unfinished npm timer reify 1658382198673
48 verbose unfinished npm timer reify:loadTrees 1658382198721
49 verbose unfinished npm timer idealTree:init 1658382198724
50 verbose code 1
51 error A complete log of this run can be found in:
51 error     C:\Users\tkhle\AppData\Local\npm-cache\_logs\2022-07-21T05_43_18_225Z-debug-0.log
```

**Comment by Th2mas** [comment]
Additional information: Trying to install the dependencies with Yarn v.1.22.15 works.
Do you have any preferred package manager?

**Comment by Th2mas** [comment]
Since I'm an aspiring contributor, I would like to tackle this issue myself. Do you agree?
