### ISSUE TITLE
Could not load PIO Account information

### ISSUE THREAD

**Issue by turgaycinbat** [platformio/platformio-home#6260]
PIO Core Call Error: "AccountNotAuthorized: You are not authorized! Please log in to PlatformIO Account."PlatformIO: Loading tasks...

**Comment by turgaycinbat** [comment]
command 'platformio-ide.build' not found

**Comment by turgaycinbat** [comment]
PS C:\Users\Nokta Bilgisayar\Marlin-2.1.2.1\Marlin-2.1.2.1> platformio run --target uplPS C:\Users\Nokta Bilgisayar\Marlin-2.1.2.1\Marlin-2.1.2.1> platformio run --target upload --silent -e mega2560
oad --silent -e mega2560
Tool Manager: Installing platformio/tool-avrdude @ ~1.60300.0
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Tool Manager: tool-avrdude@1.60300.200527 has been installed!
In file included from Marlin\src\HAL\AVR\../../inc/MarlinConfig.h:55:0,
                 from Marlin\src\HAL\AVR\HAL.cpp:24:
Marlin\src\HAL\AVR\../../inc/../core/serial.h:367:37: error: 'LOGICAL_AXIS_NAMES_LBL' was not declared in this scope
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                                     ^
Marlin\src\HAL\AVR\../../inc/../core/serial.h:357:19: note: in definition of macro '_N_LBL'
 #define _N_LBL(N) N##_LBL
                   ^
Marlin\src\HAL\AVR\../../inc/../core/macros.h:735:3: note: in expansion of macro '_N_LBL_A'
   _MAP_OP(A)                             \
   ^~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/macros.h:741:31: note: in expansion of macro '_MAPLIST'
 #define MAPLIST(OP,V...) EVAL(_MAPLIST(OP,V))
                               ^~~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/serial.h:367:19: note: in expansion of macro 'MAPLIST'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                   ^~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/serial.h:367:37: note: suggested alternative: 'LOGICAL_AXIS_DECL'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                                     ^
Marlin\src\HAL\AVR\../../inc/../core/serial.h:357:19: note: in definition of macro '_N_LBL'
 #define _N_LBL(N) N##_LBL
                   ^
Marlin\src\HAL\AVR\../../inc/../core/macros.h:735:3: note: in expansion of macro '_N_LBL_A'
   _MAP_OP(A)                             \
   ^~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/macros.h:741:31: note: in expansion of macro '_MAPLIST'
 #define MAPLIST(OP,V...) EVAL(_MAPLIST(OP,V))
                               ^~~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/serial.h:367:19: note: in expansion of macro 'MAPLIST'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                   ^~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/serial.h:359:31: error: expected primary-expression before ']' token
 #define _N_LBL_A(N) _N_LBL(N)[]
                               ^
Marlin\src\HAL\AVR\../../inc/../core/macros.h:735:3: note: in expansion of macro '_N_LBL_A'
   _MAP_OP(A)                             \
   ^~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/macros.h:741:31: note: in expansion of macro '_MAPLIST'
 #define MAPLIST(OP,V...) EVAL(_MAPLIST(OP,V))
                               ^~~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/serial.h:367:19: note: in expansion of macro 'MAPLIST'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                   ^~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/serial.h:361:22: error: redefinition of 'const char EVAL'
 #define _SP_N_LBL(N) SP_##N##_LBL
                      ^
Marlin\src\HAL\AVR\../../inc/../core/serial.h:363:24: note: in expansion of macro '_SP_N_LBL'
 #define _SP_N_LBL_A(N) _SP_N_LBL(N)[]
                        ^~~~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/macros.h:735:3: note: in expansion of macro '_SP_N_LBL_A'
   _MAP_OP(A)                             \
   ^~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/macros.h:741:31: note: in expansion of macro '_MAPLIST'
 #define MAPLIST(OP,V...) EVAL(_MAPLIST(OP,V))
                               ^~~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/serial.h:367:58: note: in expansion of macro 'MAPLIST'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                                                          ^~~~~~~
In file included from Marlin\src\HAL\AVR\../../inc/MarlinConfigPre.h:37:0,
                 from Marlin\src\HAL\AVR\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\AVR\HAL.cpp:24:
Marlin\src\HAL\AVR\../../inc/../core/macros.h:741:26: note: 'const char EVAL' previously defined here
 #define MAPLIST(OP,V...) EVAL(_MAPLIST(OP,V))
                          ^
Marlin\src\HAL\AVR\../../inc/../core/serial.h:367:19: note: in expansion of macro 'MAPLIST'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                   ^~~~~~~
In file included from Marlin\src\HAL\AVR\../../inc/MarlinConfig.h:55:0,
                 from Marlin\src\HAL\AVR\HAL.cpp:24:
Marlin\src\HAL\AVR\../../inc/../core/serial.h:361:22: error: 'SP_LOGICAL_AXIS_NAMES_LBL' was not declared in this scope
 #define _SP_N_LBL(N) SP_##N##_LBL
                      ^
Marlin\src\HAL\AVR\../../inc/../core/serial.h:363:24: note: in expansion of macro '_SP_N_LBL'
 #define _SP_N_LBL_A(N) _SP_N_LBL(N)[]
                        ^~~~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/macros.h:735:3: note: in expansion of macro '_SP_N_LBL_A'
   _MAP_OP(A)                             \
   ^~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/macros.h:741:31: note: in expansion of macro '_MAPLIST'
 #define MAPLIST(OP,V...) EVAL(_MAPLIST(OP,V))
                               ^~~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/serial.h:367:58: note: in expansion of macro 'MAPLIST'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                                                          ^~~~~~~
In file included from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:55:0,
                 from Marlin\src\HAL\shared\Delay.cpp:25:
Marlin\src\HAL\shared\../../inc/../core/serial.h:367:37: error: 'LOGICAL_AXIS_NAMES_LBL' was not declared in this scope
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                                     ^
Marlin\src\HAL\shared\../../inc/../core/serial.h:357:19: note: in definition of macro '_N_LBL'
 #define _N_LBL(N) N##_LBL
                   ^
Marlin\src\HAL\shared\../../inc/../core/macros.h:735:3: note: in expansion of macro '_N_LBL_A'
   _MAP_OP(A)                             \
   ^~~~~~~
Marlin\src\HAL\shared\../../inc/../core/macros.h:741:31: note: in expansion of macro '_MAPLIST'
 #define MAPLIST(OP,V...) EVAL(_MAPLIST(OP,V))
                               ^~~~~~~~
Marlin\src\HAL\shared\../../inc/../core/serial.h:367:19: note: in expansion of macro 'MAPLIST'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                   ^~~~~~~
Marlin\src\HAL\shared\../../inc/../core/serial.h:367:37: note: suggested alternative: 'LOGICAL_AXIS_DECL'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                                     ^
Marlin\src\HAL\shared\../../inc/../core/serial.h:357:19: note: in definition of macro '_N_LBL'
 #define _N_LBL(N) N##_LBL
                   ^
Marlin\src\HAL\shared\../../inc/../core/macros.h:735:3: note: in expansion of macro '_N_LBL_A'
   _MAP_OP(A)                             \
   ^~~~~~~
Marlin\src\HAL\shared\../../inc/../core/macros.h:741:31: note: in expansion of macro '_MAPLIST'
 #define MAPLIST(OP,V...) EVAL(_MAPLIST(OP,V))
                               ^~~~~~~~
Marlin\src\HAL\shared\../../inc/../core/serial.h:367:19: note: in expansion of macro 'MAPLIST'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                   ^~~~~~~
Marlin\src\HAL\shared\../../inc/../core/serial.h:359:31: error: expected primary-expression before ']' token
 #define _N_LBL_A(N) _N_LBL(N)[]
                               ^
Marlin\src\HAL\shared\../../inc/../core/macros.h:735:3: note: in expansion of macro '_N_LBL_A'
   _MAP_OP(A)                             \
   ^~~~~~~
Marlin\src\HAL\shared\../../inc/../core/macros.h:741:31: note: in expansion of macro '_MAPLIST'
 #define MAPLIST(OP,V...) EVAL(_MAPLIST(OP,V))
                               ^~~~~~~~
Marlin\src\HAL\shared\../../inc/../core/serial.h:367:19: note: in expansion of macro 'MAPLIST'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                   ^~~~~~~
Marlin\src\HAL\shared\../../inc/../core/serial.h:361:22: error: redefinition of 'const 
char EVAL'
 #define _SP_N_LBL(N) SP_##N##_LBL
                      ^
Marlin\src\HAL\shared\../../inc/../core/serial.h:363:24: note: in expansion of macro '_SP_N_LBL'
 #define _SP_N_LBL_A(N) _SP_N_LBL(N)[]
                        ^~~~~~~~~
Marlin\src\HAL\shared\../../inc/../core/macros.h:735:3: note: in expansion of macro '_SP_N_LBL_A'
   _MAP_OP(A)                             \
   ^~~~~~~
Marlin\src\HAL\shared\../../inc/../core/macros.h:741:31: note: in expansion of macro '_MAPLIST'

**Comment by turgaycinbat** [comment]
PS C:\Users\Nokta Bilgisayar\Marlin-2.1.2.1\Marlin-2.1.2.1> platformio run --target uplPS C:\Users\Nokta Bilgisayar\Marlin-2.1.2.1\Marlin-2.1.2.1> platformio run --target upload --silent -e mega2560
oad --silent -e mega2560
Tool Manager: Installing platformio/tool-avrdude @ ~1.60300.0
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Tool Manager: tool-avrdude@1.60300.200527 has been installed!
In file included from Marlin\src\HAL\AVR\../../inc/MarlinConfig.h:55:0,
                 from Marlin\src\HAL\AVR\HAL.cpp:24:
Marlin\src\HAL\AVR\../../inc/../core/serial.h:367:37: error: 'LOGICAL_AXIS_NAMES_LBL' was not declared in this scope
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                                     ^
Marlin\src\HAL\AVR\../../inc/../core/serial.h:357:19: note: in definition of macro '_N_LBL'
 #define _N_LBL(N) N##_LBL
                   ^
Marlin\src\HAL\AVR\../../inc/../core/macros.h:735:3: note: in expansion of macro '_N_LBL_A'
   _MAP_OP(A)                             \
   ^~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/macros.h:741:31: note: in expansion of macro '_MAPLIST'
 #define MAPLIST(OP,V...) EVAL(_MAPLIST(OP,V))
                               ^~~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/serial.h:367:19: note: in expansion of macro 'MAPLIST'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                   ^~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/serial.h:367:37: note: suggested alternative: 'LOGICAL_AXIS_DECL'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                                     ^
Marlin\src\HAL\AVR\../../inc/../core/serial.h:357:19: note: in definition of macro '_N_LBL'
 #define _N_LBL(N) N##_LBL
                   ^
Marlin\src\HAL\AVR\../../inc/../core/macros.h:735:3: note: in expansion of macro '_N_LBL_A'
   _MAP_OP(A)                             \
   ^~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/macros.h:741:31: note: in expansion of macro '_MAPLIST'
 #define MAPLIST(OP,V...) EVAL(_MAPLIST(OP,V))
                               ^~~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/serial.h:367:19: note: in expansion of macro 'MAPLIST'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                   ^~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/serial.h:359:31: error: expected primary-expression before ']' token
 #define _N_LBL_A(N) _N_LBL(N)[]
                               ^
Marlin\src\HAL\AVR\../../inc/../core/macros.h:735:3: note: in expansion of macro '_N_LBL_A'
   _MAP_OP(A)                             \
   ^~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/macros.h:741:31: note: in expansion of macro '_MAPLIST'
 #define MAPLIST(OP,V...) EVAL(_MAPLIST(OP,V))
                               ^~~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/serial.h:367:19: note: in expansion of macro 'MAPLIST'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                   ^~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/serial.h:361:22: error: redefinition of 'const char EVAL'
 #define _SP_N_LBL(N) SP_##N##_LBL
                      ^
Marlin\src\HAL\AVR\../../inc/../core/serial.h:363:24: note: in expansion of macro '_SP_N_LBL'
 #define _SP_N_LBL_A(N) _SP_N_LBL(N)[]
                        ^~~~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/macros.h:735:3: note: in expansion of macro '_SP_N_LBL_A'
   _MAP_OP(A)                             \
   ^~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/macros.h:741:31: note: in expansion of macro '_MAPLIST'
 #define MAPLIST(OP,V...) EVAL(_MAPLIST(OP,V))
                               ^~~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/serial.h:367:58: note: in expansion of macro 'MAPLIST'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                                                          ^~~~~~~
In file included from Marlin\src\HAL\AVR\../../inc/MarlinConfigPre.h:37:0,
                 from Marlin\src\HAL\AVR\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\AVR\HAL.cpp:24:
Marlin\src\HAL\AVR\../../inc/../core/macros.h:741:26: note: 'const char EVAL' previously defined here
 #define MAPLIST(OP,V...) EVAL(_MAPLIST(OP,V))
                          ^
Marlin\src\HAL\AVR\../../inc/../core/serial.h:367:19: note: in expansion of macro 'MAPLIST'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                   ^~~~~~~
In file included from Marlin\src\HAL\AVR\../../inc/MarlinConfig.h:55:0,
                 from Marlin\src\HAL\AVR\HAL.cpp:24:
Marlin\src\HAL\AVR\../../inc/../core/serial.h:361:22: error: 'SP_LOGICAL_AXIS_NAMES_LBL' was not declared in this scope
 #define _SP_N_LBL(N) SP_##N##_LBL
                      ^
Marlin\src\HAL\AVR\../../inc/../core/serial.h:363:24: note: in expansion of macro '_SP_N_LBL'
 #define _SP_N_LBL_A(N) _SP_N_LBL(N)[]
                        ^~~~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/macros.h:735:3: note: in expansion of macro '_SP_N_LBL_A'
   _MAP_OP(A)                             \
   ^~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/macros.h:741:31: note: in expansion of macro '_MAPLIST'
 #define MAPLIST(OP,V...) EVAL(_MAPLIST(OP,V))
                               ^~~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/serial.h:367:58: note: in expansion of macro 'MAPLIST'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                                                          ^~~~~~~
In file included from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:55:0,
                 from Marlin\src\HAL\shared\Delay.cpp:25:
Marlin\src\HAL\shared\../../inc/../core/serial.h:367:37: error: 'LOGICAL_AXIS_NAMES_LBL' was not declared in this scope
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                                     ^
Marlin\src\HAL\shared\../../inc/../core/serial.h:357:19: note: in definition of macro '_N_LBL'
 #define _N_LBL(N) N##_LBL
                   ^
Marlin\src\HAL\shared\../../inc/../core/macros.h:735:3: note: in expansion of macro '_N_LBL_A'
   _MAP_OP(A)                             \
   ^~~~~~~
Marlin\src\HAL\shared\../../inc/../core/macros.h:741:31: note: in expansion of macro '_MAPLIST'
 #define MAPLIST(OP,V...) EVAL(_MAPLIST(OP,V))
                               ^~~~~~~~
Marlin\src\HAL\shared\../../inc/../core/serial.h:367:19: note: in expansion of macro 'MAPLIST'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                   ^~~~~~~
Marlin\src\HAL\shared\../../inc/../core/serial.h:367:37: note: suggested alternative: 'LOGICAL_AXIS_DECL'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                                     ^
Marlin\src\HAL\shared\../../inc/../core/serial.h:357:19: note: in definition of macro '_N_LBL'
 #define _N_LBL(N) N##_LBL
                   ^
Marlin\src\HAL\shared\../../inc/../core/macros.h:735:3: note: in expansion of macro '_N_LBL_A'
   _MAP_OP(A)                             \
   ^~~~~~~
Marlin\src\HAL\shared\../../inc/../core/macros.h:741:31: note: in expansion of macro '_MAPLIST'
 #define MAPLIST(OP,V...) EVAL(_MAPLIST(OP,V))
                               ^~~~~~~~
Marlin\src\HAL\shared\../../inc/../core/serial.h:367:19: note: in expansion of macro 'MAPLIST'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                   ^~~~~~~
Marlin\src\HAL\shared\../../inc/../core/serial.h:359:31: error: expected primary-expression before ']' token
 #define _N_LBL_A(N) _N_LBL(N)[]
                               ^
Marlin\src\HAL\shared\../../inc/../core/macros.h:735:3: note: in expansion of macro '_N_LBL_A'
   _MAP_OP(A)                             \
   ^~~~~~~
Marlin\src\HAL\shared\../../inc/../core/macros.h:741:31: note: in expansion of macro '_MAPLIST'
 #define MAPLIST(OP,V...) EVAL(_MAPLIST(OP,V))
                               ^~~~~~~~
Marlin\src\HAL\shared\../../inc/../core/serial.h:367:19: note: in expansion of macro 'MAPLIST'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                   ^~~~~~~
Marlin\src\HAL\shared\../../inc/../core/serial.h:361:22: error: redefinition of 'const 
char EVAL'
 #define _SP_N_LBL(N) SP_##N##_LBL
                      ^
Marlin\src\HAL\shared\../../inc/../core/serial.h:363:24: note: in expansion of macro '_SP_N_LBL'
 #define _SP_N_LBL_A(N) _SP_N_LBL(N)[]
                        ^~~~~~~~~
Marlin\src\HAL\shared\../../inc/../core/macros.h:735:3: note: in expansion of macro '_SP_N_LBL_A'
   _MAP_OP(A)                             \
   ^~~~~~~
Marlin\src\HAL\shared\../../inc/../core/macros.h:741:31: note: in expansion of macro '_MAPLIST'
 #define MAPLIST(OP,V...) EVAL(_MAPLIST(OP,V))
                               ^~~~~~~~
Marlin\src\HAL\shared\../../inc/../core/serial.h:367:58: note: in expansion of macro 'MAPLIST'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                                                          ^~~~~~~
In file included from Marlin\src\HAL\shared\../../inc/MarlinConfigPre.h:37:0,
                 from Marlin\src\HAL\shared\Delay.h:24,
                 from Marlin\src\HAL\shared\Delay.cpp:23:
Marlin\src\HAL\shared\../../inc/../core/macros.h:741:26: note: 'const char EVAL' previously defined here
 #define MAPLIST(OP,V...) EVAL(_MAPLIST(OP,V))
                          ^
Marlin\src\HAL\shared\../../inc/../core/serial.h:367:19: note: in expansion of macro 'MAPLIST'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                   ^~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/serial.h:361:22: note: suggested alternative: 'LOGICAL_AXIS_DECL'
 #define _SP_N_LBL(N) SP_##N##_LBL
                      ^
Marlin\src\HAL\AVR\../../inc/../core/serial.h:363:24: note: in expansion of macro '_SP_N_LBL'
 #define _SP_N_LBL_A(N) _SP_N_LBL(N)[]
                        ^~~~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/macros.h:735:3: note: in expansion of macro '_SP_N_LBL_A'
   _MAP_OP(A)                             \
   ^~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/macros.h:741:31: note: in expansion of macro '_MAPLIST'
 #define MAPLIST(OP,V...) EVAL(_MAPLIST(OP,V))
                               ^~~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/serial.h:367:58: note: in expansion of macro 'MAPLIST'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                                                          ^~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/serial.h:363:37: error: expected primary-expression before ']' token
 #define _SP_N_LBL_A(N) _SP_N_LBL(N)[]
                                     ^
Marlin\src\HAL\AVR\../../inc/../core/macros.h:735:3: note: in expansion of macro '_SP_N_LBL_A'
   _MAP_OP(A)                             \
   ^~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/macros.h:741:31: note: in expansion of macro '_MAPLIST'
 #define MAPLIST(OP,V...) EVAL(_MAPLIST(OP,V))
                               ^~~~~~~~
Marlin\src\HAL\AVR\../../inc/../core/serial.h:367:58: note: in expansion of macro 'MAPLIST'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                                                          ^~~~~~~
In file included from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:55:0,
                 from Marlin\src\HAL\shared\Delay.cpp:25:
Marlin\src\HAL\shared\../../inc/../core/serial.h:361:22: error: 'SP_LOGICAL_AXIS_NAMES_LBL' was not declared in this scope
 #define _SP_N_LBL(N) SP_##N##_LBL
                      ^
Marlin\src\HAL\shared\../../inc/../core/serial.h:363:24: note: in expansion of macro '_SP_N_LBL'
 #define _SP_N_LBL_A(N) _SP_N_LBL(N)[]
                        ^~~~~~~~~
Marlin\src\HAL\shared\../../inc/../core/macros.h:735:3: note: in expansion of macro '_SP_N_LBL_A'
   _MAP_OP(A)                             \
   ^~~~~~~
Marlin\src\HAL\shared\../../inc/../core/macros.h:741:31: note: in expansion of macro '_MAPLIST'
 #define MAPLIST(OP,V...) EVAL(_MAPLIST(OP,V))
                               ^~~~~~~~
Marlin\src\HAL\shared\../../inc/../core/serial.h:367:58: note: in expansion of macro 'MAPLIST'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                                                          ^~~~~~~
compilation terminated due to -fmax-errors=5.
Marlin\src\HAL\shared\../../inc/../core/serial.h:361:22: note: suggested alternative: 'LOGICAL_AXIS_DECL'
 #define _SP_N_LBL(N) SP_##N##_LBL
                      ^
Marlin\src\HAL\shared\../../inc/../core/serial.h:363:24: note: in expansion of macro '_SP_N_LBL'
 #define _SP_N_LBL_A(N) _SP_N_LBL(N)[]
                        ^~~~~~~~~
Marlin\src\HAL\shared\../../inc/../core/macros.h:735:3: note: in expansion of macro '_SP_N_LBL_A'
   _MAP_OP(A)                             \
   ^~~~~~~
Marlin\src\HAL\shared\../../inc/../core/macros.h:741:31: note: in expansion of macro '_MAPLIST'
 #define MAPLIST(OP,V...) EVAL(_MAPLIST(OP,V))
                               ^~~~~~~~
Marlin\src\HAL\shared\../../inc/../core/serial.h:367:58: note: in expansion of macro 'MAPLIST'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                                                          ^~~~~~~
Marlin\src\HAL\shared\../../inc/../core/serial.h:363:37: error: expected primary-expression before ']' token
 #define _SP_N_LBL_A(N) _SP_N_LBL(N)[]
                                     ^
Marlin\src\HAL\shared\../../inc/../core/macros.h:735:3: note: in expansion of macro '_SP_N_LBL_A'
   _MAP_OP(A)                             \
   ^~~~~~~
Marlin\src\HAL\shared\../../inc/../core/macros.h:741:31: note: in expansion of macro '_MAPLIST'
 #define MAPLIST(OP,V...) EVAL(_MAPLIST(OP,V))
                               ^~~~~~~~
Marlin\src\HAL\shared\../../inc/../core/serial.h:367:58: note: in expansion of macro 'MAPLIST'
                   MAPLIST(_N_LBL_A, LOGICAL_AXIS_NAMES), MAPLIST(_SP_N_LBL_A, LOGICAL_AXIS_NAMES);
                                                          ^~~~~~~
compilation terminated due to -fmax-errors=5.
*** [.pio\build\mega2560\src\src\HAL\AVR\HAL.cpp.o] Error 1
*** [.pio\build\mega2560\src\src\HAL\shared\Delay.cpp.o] Error 1
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Nokta Bilgisayar\\Marlin-2.1.2.1\\Marlin-2.1.2.1\\.pio\\build\\mega2560\\.sconsign311.tmp':
  File "C:\Users\Nokta Bilgisayar\.platformio\packages\tool-scons\scons-local-4.5.2\SCons\Script\Main.py", line 1412:
    _exec_main(parser, values)
  File "C:\Users\Nokta Bilgisayar\.platformio\packages\tool-scons\scons-local-4.5.2\SCons\Script\Main.py", line 1374:
    _main(parser)
  File "C:\Users\Nokta Bilgisayar\.platformio\packages\tool-scons\scons-local-4.5.2\SCons\Script\Main.py", line 1154:
    nodes = _build_targets(fs, options, targets, target_top)
  File "C:\Users\Nokta Bilgisayar\.platformio\packages\tool-scons\scons-local-4.5.2\SCons\Script\Main.py", line 1349:
    jobs.run(postfunc = jobs_postfunc)
  File "C:\Users\Nokta Bilgisayar\.platformio\packages\tool-scons\scons-local-4.5.2\SCons\Taskmaster\Job.py", line 125:
    postfunc()
  File "C:\Users\Nokta Bilgisayar\.platformio\packages\tool-scons\scons-local-4.5.2\SCons\Script\Main.py", line 1346:
    SCons.SConsign.write()
  File "C:\Users\Nokta Bilgisayar\.platformio\packages\tool-scons\scons-local-4.5.2\SCons\SConsign.py", line 133:
    syncmethod()
  File "C:\Users\Nokta Bilgisayar\.platformio\packages\tool-scons\scons-local-4.5.2\SCons\dblite.py", line 148:
    with self._open(self._tmp_name, "wb", self._mode) as f:
Exception ignored in: <function dblite.__del__ at 0x000001DC19524D60>
Traceback (most recent call last):
  File "C:\Users\Nokta Bilgisayar\.platformio\packages\tool-scons\scons-local-4.5.2\SCo  File "C:\Users\Nokta Bilgisayar\.platformio\packages\tool-scons\scons-local-4.5.2\SCons\dblite.py", line 141, in close
  File "C:\Users\Nokta Bilgisayar\.platformio\packages\tool-scons\scons-local-4.5.2\SCons\dblite.py", line 148, in sync
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Nokta Bilgisayar\\Marlin-2.1.2.1\\Marlin-2.1.2.1\\.pio\\build\\mega2560\\.sconsign311.tmp'
============================ [FAILED] Took 219.40 seconds ============================ 

Environment    Status    Duration
-------------  --------  ------------
mega2560       FAILED    00:03:39.401
======================== 1 failed, 0 succeeded in 00:03:39.401 ========================PS C:\Users\Nokta Bilgisayar\Marlin-2.1.2.1\Marlin-2.1.2.1> echo "done" >"C:\Users\NOKTAB~1\AppData\Local\Temp\ipc"
PS C:\Users\Nokta Bilgisayar\Marlin-2.1.2.1\Marlin-2.1.2.1>
